docker push StockDesk/clientmanagementapi:1.0
docker push StockDesk/clientmanagementapi:2.0
docker push StockDesk/webapp:1.0
docker push StockDesk/portfoliomanagementeventhandler:1.0
docker push StockDesk/timeservice:1.0
docker push StockDesk/notificationservice:1.0
docker push StockDesk/invoiceservice:1.0
docker push StockDesk/auditlogservice:1.0
docker push StockDesk/portfoliomanagementapi:1.0
docker push StockDesk/stockmanagementapi:1.0